name: "Particle Build"

on: 
  workflow_dispatch:
#   push:
#     branches: 
#       - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: addnab/docker-run-action@v3
      with:
        image: particle/buildpack-particle-firmware:3.0.0-electron
        options: -v ${{ github.workspace }}:/input -v ${{ github.workspace }}:/output -e PLATFORM_ID=10 particle/buildpack-particle-firmware:3.0.0
