name: Compile Firmware

on: [push, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile application
        id: compile
        uses: particle-iot/compile-action@v1
        with:
            particle-platform-name: 'electron'
            device-os-version: '3.0.0'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware-artifact
          path: |
              ${{ steps.compile.outputs.firmware-path }}
              ${{ steps.compile.outputs.target-path }}
